/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatHistoryResponse,
  GetVideoChatHistoryParams,
  PagePublicVideoResponse,
  PublicVideoResponse,
  SearchVideosParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 동영상 목록 조회
 */
export const searchVideos = (
  params: SearchVideosParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PagePublicVideoResponse>(
    { url: `/videos`, method: "GET", params, signal },
    options,
  );
};

export const getSearchVideosQueryKey = (params?: SearchVideosParams) => {
  return [`/videos`, ...(params ? [params] : [])] as const;
};

export const getSearchVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVideos>>> = ({
    signal,
  }) => searchVideos(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchVideos>>
>;
export type SearchVideosQueryError = unknown;

export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 목록 조회
 */

export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 단건 조회
 */
export const getVideoByUuid = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PublicVideoResponse>(
    { url: `/videos/${uuid}`, method: "GET", signal },
    options,
  );
};

export const getGetVideoByUuidQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}`] as const;
};

export const getGetVideoByUuidQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoByUuidQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoByUuid>>> = ({
    signal,
  }) => getVideoByUuid(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoByUuid>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoByUuidQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoByUuid>>
>;
export type GetVideoByUuidQueryError = unknown;

export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoByUuid>>,
          TError,
          Awaited<ReturnType<typeof getVideoByUuid>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoByUuid>>,
          TError,
          Awaited<ReturnType<typeof getVideoByUuid>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 단건 조회
 */

export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoByUuidQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary HLS 세그먼트 파일 조회
 */
export const getVideoSegment = (
  uuid: string,
  filename: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/videos/${uuid}/${filename}`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoSegmentQueryKey = (
  uuid?: string,
  filename?: string,
) => {
  return [`/videos/${uuid}/${filename}`] as const;
};

export const getGetVideoSegmentQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoSegmentQueryKey(uuid, filename);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSegment>>> = ({
    signal,
  }) => getVideoSegment(uuid, filename, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(uuid && filename),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoSegment>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSegmentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSegment>>
>;
export type GetVideoSegmentQueryError = unknown;

export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSegment>>,
          TError,
          Awaited<ReturnType<typeof getVideoSegment>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSegment>>,
          TError,
          Awaited<ReturnType<typeof getVideoSegment>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary HLS 세그먼트 파일 조회
 */

export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoSegmentQueryOptions(uuid, filename, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 썸네일 조회
 */
export const getVideoThumbnail = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/videos/${uuid}/thumbnail`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoThumbnailQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}/thumbnail`] as const;
};

export const getGetVideoThumbnailQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoThumbnailQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoThumbnail>>
  > = ({ signal }) => getVideoThumbnail(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoThumbnail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoThumbnailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoThumbnail>>
>;
export type GetVideoThumbnailQueryError = unknown;

export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getVideoThumbnail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getVideoThumbnail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 썸네일 조회
 */

export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoThumbnailQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary HLS 플레이리스트 조회
 */
export const getVideoPlaylist = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/videos/${uuid}/playlist.m3u8`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoPlaylistQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}/playlist.m3u8`] as const;
};

export const getGetVideoPlaylistQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoPlaylistQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoPlaylist>>
  > = ({ signal }) => getVideoPlaylist(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoPlaylist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoPlaylistQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoPlaylist>>
>;
export type GetVideoPlaylistQueryError = unknown;

export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoPlaylist>>,
          TError,
          Awaited<ReturnType<typeof getVideoPlaylist>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoPlaylist>>,
          TError,
          Awaited<ReturnType<typeof getVideoPlaylist>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary HLS 플레이리스트 조회
 */

export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoPlaylistQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 채팅 이력 조회
 */
export const getVideoChatHistory = (
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<ChatHistoryResponse[]>(
    { url: `/videos/${uuid}/chat`, method: "GET", params, signal },
    options,
  );
};

export const getGetVideoChatHistoryQueryKey = (
  uuid?: string,
  params?: GetVideoChatHistoryParams,
) => {
  return [`/videos/${uuid}/chat`, ...(params ? [params] : [])] as const;
};

export const getGetVideoChatHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoChatHistoryQueryKey(uuid, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoChatHistory>>
  > = ({ signal }) => getVideoChatHistory(uuid, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoChatHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoChatHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoChatHistory>>
>;
export type GetVideoChatHistoryQueryError = unknown;

export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoChatHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoChatHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoChatHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoChatHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 채팅 이력 조회
 */

export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoChatHistoryQueryOptions(
    uuid,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
