/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetVideoChatHistoryParams,
  PageVideoSearchResponse,
  SearchVideosParams,
  VideoChatHistorySearchResponse,
  VideoGetResponse,
  VideoViewerHistoryGetResponse,
  WatchHistoryGetResponse,
  WatchHistorySaveRequest,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 동영상 시청 기록 조회
 */
export const getVideoWatchHistory = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<WatchHistoryGetResponse>(
    { url: `/videos/${uuid}/watch-history`, method: "GET", signal },
    options,
  );
};

export const getGetVideoWatchHistoryQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}/watch-history`] as const;
};

export const getGetVideoWatchHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoWatchHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoWatchHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoWatchHistoryQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoWatchHistory>>
  > = ({ signal }) => getVideoWatchHistory(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoWatchHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoWatchHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoWatchHistory>>
>;
export type GetVideoWatchHistoryQueryError = unknown;

export function useGetVideoWatchHistory<
  TData = Awaited<ReturnType<typeof getVideoWatchHistory>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoWatchHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoWatchHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoWatchHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoWatchHistory<
  TData = Awaited<ReturnType<typeof getVideoWatchHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoWatchHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoWatchHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoWatchHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoWatchHistory<
  TData = Awaited<ReturnType<typeof getVideoWatchHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoWatchHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 시청 기록 조회
 */

export function useGetVideoWatchHistory<
  TData = Awaited<ReturnType<typeof getVideoWatchHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoWatchHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoWatchHistoryQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 시청 위치 저장
 */
export const saveVideoWatchHistory = (
  uuid: string,
  watchHistorySaveRequest: WatchHistorySaveRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>(
    {
      url: `/videos/${uuid}/watch-history`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: watchHistorySaveRequest,
      signal,
    },
    options,
  );
};

export const getSaveVideoWatchHistoryMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveVideoWatchHistory>>,
    TError,
    { uuid: string; data: WatchHistorySaveRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveVideoWatchHistory>>,
  TError,
  { uuid: string; data: WatchHistorySaveRequest },
  TContext
> => {
  const mutationKey = ["saveVideoWatchHistory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveVideoWatchHistory>>,
    { uuid: string; data: WatchHistorySaveRequest }
  > = (props) => {
    const { uuid, data } = props ?? {};

    return saveVideoWatchHistory(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveVideoWatchHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof saveVideoWatchHistory>>
>;
export type SaveVideoWatchHistoryMutationBody = WatchHistorySaveRequest;
export type SaveVideoWatchHistoryMutationError = unknown;

/**
 * @summary 동영상 시청 위치 저장
 */
export const useSaveVideoWatchHistory = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof saveVideoWatchHistory>>,
      TError,
      { uuid: string; data: WatchHistorySaveRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof saveVideoWatchHistory>>,
  TError,
  { uuid: string; data: WatchHistorySaveRequest },
  TContext
> => {
  const mutationOptions = getSaveVideoWatchHistoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 동영상 목록 조회
 */
export const searchVideos = (
  params: SearchVideosParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageVideoSearchResponse>(
    { url: `/videos`, method: "GET", params, signal },
    options,
  );
};

export const getSearchVideosQueryKey = (params?: SearchVideosParams) => {
  return [`/videos`, ...(params ? [params] : [])] as const;
};

export const getSearchVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVideos>>> = ({
    signal,
  }) => searchVideos(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchVideos>>
>;
export type SearchVideosQueryError = unknown;

export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 목록 조회
 */

export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 단건 조회
 */
export const getVideoByUuid = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoGetResponse>(
    { url: `/videos/${uuid}`, method: "GET", signal },
    options,
  );
};

export const getGetVideoByUuidQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}`] as const;
};

export const getGetVideoByUuidQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoByUuidQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoByUuid>>> = ({
    signal,
  }) => getVideoByUuid(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoByUuid>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoByUuidQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoByUuid>>
>;
export type GetVideoByUuidQueryError = unknown;

export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoByUuid>>,
          TError,
          Awaited<ReturnType<typeof getVideoByUuid>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoByUuid>>,
          TError,
          Awaited<ReturnType<typeof getVideoByUuid>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 단건 조회
 */

export function useGetVideoByUuid<
  TData = Awaited<ReturnType<typeof getVideoByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoByUuid>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoByUuidQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary HLS 세그먼트 파일 조회
 */
export const getVideoSegment = (
  uuid: string,
  filename: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/videos/${uuid}/${filename}`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoSegmentQueryKey = (
  uuid?: string,
  filename?: string,
) => {
  return [`/videos/${uuid}/${filename}`] as const;
};

export const getGetVideoSegmentQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoSegmentQueryKey(uuid, filename);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSegment>>> = ({
    signal,
  }) => getVideoSegment(uuid, filename, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(uuid && filename),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoSegment>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSegmentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSegment>>
>;
export type GetVideoSegmentQueryError = unknown;

export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSegment>>,
          TError,
          Awaited<ReturnType<typeof getVideoSegment>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSegment>>,
          TError,
          Awaited<ReturnType<typeof getVideoSegment>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary HLS 세그먼트 파일 조회
 */

export function useGetVideoSegment<
  TData = Awaited<ReturnType<typeof getVideoSegment>>,
  TError = unknown,
>(
  uuid: string,
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoSegment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoSegmentQueryOptions(uuid, filename, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 시청자 수 이력 조회
 */
export const getVideoViewerHistory = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoViewerHistoryGetResponse[]>(
    { url: `/videos/${uuid}/viewer-history`, method: "GET", signal },
    options,
  );
};

export const getGetVideoViewerHistoryQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}/viewer-history`] as const;
};

export const getGetVideoViewerHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoViewerHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoViewerHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoViewerHistoryQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoViewerHistory>>
  > = ({ signal }) => getVideoViewerHistory(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoViewerHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoViewerHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoViewerHistory>>
>;
export type GetVideoViewerHistoryQueryError = unknown;

export function useGetVideoViewerHistory<
  TData = Awaited<ReturnType<typeof getVideoViewerHistory>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoViewerHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoViewerHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoViewerHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoViewerHistory<
  TData = Awaited<ReturnType<typeof getVideoViewerHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoViewerHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoViewerHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoViewerHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoViewerHistory<
  TData = Awaited<ReturnType<typeof getVideoViewerHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoViewerHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 시청자 수 이력 조회
 */

export function useGetVideoViewerHistory<
  TData = Awaited<ReturnType<typeof getVideoViewerHistory>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoViewerHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoViewerHistoryQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 썸네일 조회
 */
export const getVideoThumbnail = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/videos/${uuid}/thumbnail`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoThumbnailQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}/thumbnail`] as const;
};

export const getGetVideoThumbnailQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoThumbnailQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoThumbnail>>
  > = ({ signal }) => getVideoThumbnail(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoThumbnail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoThumbnailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoThumbnail>>
>;
export type GetVideoThumbnailQueryError = unknown;

export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getVideoThumbnail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getVideoThumbnail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 썸네일 조회
 */

export function useGetVideoThumbnail<
  TData = Awaited<ReturnType<typeof getVideoThumbnail>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoThumbnail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoThumbnailQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary HLS 플레이리스트 조회
 */
export const getVideoPlaylist = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/videos/${uuid}/playlist.m3u8`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoPlaylistQueryKey = (uuid?: string) => {
  return [`/videos/${uuid}/playlist.m3u8`] as const;
};

export const getGetVideoPlaylistQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoPlaylistQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoPlaylist>>
  > = ({ signal }) => getVideoPlaylist(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoPlaylist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoPlaylistQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoPlaylist>>
>;
export type GetVideoPlaylistQueryError = unknown;

export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoPlaylist>>,
          TError,
          Awaited<ReturnType<typeof getVideoPlaylist>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoPlaylist>>,
          TError,
          Awaited<ReturnType<typeof getVideoPlaylist>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary HLS 플레이리스트 조회
 */

export function useGetVideoPlaylist<
  TData = Awaited<ReturnType<typeof getVideoPlaylist>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoPlaylist>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoPlaylistQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 채팅 이력 조회
 */
export const getVideoChatHistory = (
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoChatHistorySearchResponse[]>(
    { url: `/videos/${uuid}/chat`, method: "GET", params, signal },
    options,
  );
};

export const getGetVideoChatHistoryQueryKey = (
  uuid?: string,
  params?: GetVideoChatHistoryParams,
) => {
  return [`/videos/${uuid}/chat`, ...(params ? [params] : [])] as const;
};

export const getGetVideoChatHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoChatHistoryQueryKey(uuid, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getVideoChatHistory>>
  > = ({ signal }) => getVideoChatHistory(uuid, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoChatHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoChatHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoChatHistory>>
>;
export type GetVideoChatHistoryQueryError = unknown;

export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoChatHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoChatHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoChatHistory>>,
          TError,
          Awaited<ReturnType<typeof getVideoChatHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 채팅 이력 조회
 */

export function useGetVideoChatHistory<
  TData = Awaited<ReturnType<typeof getVideoChatHistory>>,
  TError = unknown,
>(
  uuid: string,
  params: GetVideoChatHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getVideoChatHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVideoChatHistoryQueryOptions(
    uuid,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
