/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PlatformAdminChannelResolveResponse,
  ResolveAdminPlatformChannelParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 플랫폼 채널 조회 (URL로 플랫폼·채널 인식)
 */
export const resolveAdminPlatformChannel = (
  params: ResolveAdminPlatformChannelParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PlatformAdminChannelResolveResponse>(
    { url: `/admin/platforms/resolve`, method: "GET", params, signal },
    options,
  );
};

export const getResolveAdminPlatformChannelQueryKey = (
  params?: ResolveAdminPlatformChannelParams,
) => {
  return [`/admin/platforms/resolve`, ...(params ? [params] : [])] as const;
};

export const getResolveAdminPlatformChannelQueryOptions = <
  TData = Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
  TError = unknown,
>(
  params: ResolveAdminPlatformChannelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getResolveAdminPlatformChannelQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof resolveAdminPlatformChannel>>
  > = ({ signal }) =>
    resolveAdminPlatformChannel(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ResolveAdminPlatformChannelQueryResult = NonNullable<
  Awaited<ReturnType<typeof resolveAdminPlatformChannel>>
>;
export type ResolveAdminPlatformChannelQueryError = unknown;

export function useResolveAdminPlatformChannel<
  TData = Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
  TError = unknown,
>(
  params: ResolveAdminPlatformChannelParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
          TError,
          Awaited<ReturnType<typeof resolveAdminPlatformChannel>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useResolveAdminPlatformChannel<
  TData = Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
  TError = unknown,
>(
  params: ResolveAdminPlatformChannelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
          TError,
          Awaited<ReturnType<typeof resolveAdminPlatformChannel>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useResolveAdminPlatformChannel<
  TData = Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
  TError = unknown,
>(
  params: ResolveAdminPlatformChannelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 플랫폼 채널 조회 (URL로 플랫폼·채널 인식)
 */

export function useResolveAdminPlatformChannel<
  TData = Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
  TError = unknown,
>(
  params: ResolveAdminPlatformChannelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resolveAdminPlatformChannel>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getResolveAdminPlatformChannelQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
