/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetWatchHistoriesParams,
  PageWatchHistoryListResponse,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 시청 기록 목록 조회
 */
export const getWatchHistories = (
  params: GetWatchHistoriesParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageWatchHistoryListResponse>(
    { url: `/watch-histories`, method: "GET", params, signal },
    options,
  );
};

export const getGetWatchHistoriesQueryKey = (
  params?: GetWatchHistoriesParams,
) => {
  return [`/watch-histories`, ...(params ? [params] : [])] as const;
};

export const getGetWatchHistoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getWatchHistories>>,
  TError = unknown,
>(
  params: GetWatchHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWatchHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetWatchHistoriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWatchHistories>>
  > = ({ signal }) => getWatchHistories(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWatchHistories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWatchHistoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWatchHistories>>
>;
export type GetWatchHistoriesQueryError = unknown;

export function useGetWatchHistories<
  TData = Awaited<ReturnType<typeof getWatchHistories>>,
  TError = unknown,
>(
  params: GetWatchHistoriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWatchHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchHistories>>,
          TError,
          Awaited<ReturnType<typeof getWatchHistories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWatchHistories<
  TData = Awaited<ReturnType<typeof getWatchHistories>>,
  TError = unknown,
>(
  params: GetWatchHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWatchHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchHistories>>,
          TError,
          Awaited<ReturnType<typeof getWatchHistories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWatchHistories<
  TData = Awaited<ReturnType<typeof getWatchHistories>>,
  TError = unknown,
>(
  params: GetWatchHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWatchHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 시청 기록 목록 조회
 */

export function useGetWatchHistories<
  TData = Awaited<ReturnType<typeof getWatchHistories>>,
  TError = unknown,
>(
  params: GetWatchHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWatchHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWatchHistoriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 시청 기록 전체 삭제
 */
export const deleteAllWatchHistories = (
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/watch-histories`, method: "DELETE" },
    options,
  );
};

export const getDeleteAllWatchHistoriesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAllWatchHistories>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAllWatchHistories>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["deleteAllWatchHistories"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAllWatchHistories>>,
    void
  > = () => {
    return deleteAllWatchHistories(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAllWatchHistoriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAllWatchHistories>>
>;

export type DeleteAllWatchHistoriesMutationError = unknown;

/**
 * @summary 시청 기록 전체 삭제
 */
export const useDeleteAllWatchHistories = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAllWatchHistories>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAllWatchHistories>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDeleteAllWatchHistoriesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 시청 기록 개별 삭제
 */
export const deleteWatchHistory = (
  videoUuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/watch-histories/${videoUuid}`, method: "DELETE" },
    options,
  );
};

export const getDeleteWatchHistoryMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWatchHistory>>,
    TError,
    { videoUuid: string },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWatchHistory>>,
  TError,
  { videoUuid: string },
  TContext
> => {
  const mutationKey = ["deleteWatchHistory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWatchHistory>>,
    { videoUuid: string }
  > = (props) => {
    const { videoUuid } = props ?? {};

    return deleteWatchHistory(videoUuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWatchHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteWatchHistory>>
>;

export type DeleteWatchHistoryMutationError = unknown;

/**
 * @summary 시청 기록 개별 삭제
 */
export const useDeleteWatchHistory = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteWatchHistory>>,
      TError,
      { videoUuid: string },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteWatchHistory>>,
  TError,
  { videoUuid: string },
  TContext
> => {
  const mutationOptions = getDeleteWatchHistoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
