/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 녹화 취소
 */
export const cancelAdminRecord = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/records/${id}/cancel`, method: "POST", signal },
    options,
  );
};

export const getCancelAdminRecordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelAdminRecord>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelAdminRecord>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["cancelAdminRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelAdminRecord>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return cancelAdminRecord(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelAdminRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelAdminRecord>>
>;

export type CancelAdminRecordMutationError = unknown;

/**
 * @summary 녹화 취소
 */
export const useCancelAdminRecord = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelAdminRecord>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelAdminRecord>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getCancelAdminRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
