/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminUserResponse,
  AdminUserUpdateRequest,
  PageAdminUserResponse,
  SearchAdminUsersParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 사용자 상세 조회
 */
export const getAdminUserById = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminUserResponse>(
    { url: `/admin/users/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetAdminUserByIdQueryKey = (id?: number) => {
  return [`/admin/users/${id}`] as const;
};

export const getGetAdminUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminUserById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUserById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminUserByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminUserById>>
  > = ({ signal }) => getAdminUserById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminUserById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminUserById>>
>;
export type GetAdminUserByIdQueryError = unknown;

export function useGetAdminUserById<
  TData = Awaited<ReturnType<typeof getAdminUserById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUserById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminUserById>>,
          TError,
          Awaited<ReturnType<typeof getAdminUserById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUserById<
  TData = Awaited<ReturnType<typeof getAdminUserById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUserById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminUserById>>,
          TError,
          Awaited<ReturnType<typeof getAdminUserById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUserById<
  TData = Awaited<ReturnType<typeof getAdminUserById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUserById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자 상세 조회
 */

export function useGetAdminUserById<
  TData = Awaited<ReturnType<typeof getAdminUserById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUserById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminUserByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 사용자 수정
 */
export const updateAdminUser = (
  id: number,
  adminUserUpdateRequest: AdminUserUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<AdminUserResponse>(
    {
      url: `/admin/users/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminUserUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminUser>>,
    TError,
    { id: number; data: AdminUserUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminUser>>,
  TError,
  { id: number; data: AdminUserUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminUser>>,
    { id: number; data: AdminUserUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAdminUser(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminUser>>
>;
export type UpdateAdminUserMutationBody = AdminUserUpdateRequest;
export type UpdateAdminUserMutationError = unknown;

/**
 * @summary 사용자 수정
 */
export const useUpdateAdminUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminUser>>,
      TError,
      { id: number; data: AdminUserUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminUser>>,
  TError,
  { id: number; data: AdminUserUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateAdminUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 사용자 삭제
 */
export const deleteAdminUser = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/users/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteAdminUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminUser>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdminUser>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAdminUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdminUser>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAdminUser(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdminUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminUser>>
>;

export type DeleteAdminUserMutationError = unknown;

/**
 * @summary 사용자 삭제
 */
export const useDeleteAdminUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdminUser>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdminUser>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteAdminUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 사용자 목록 조회
 */
export const searchAdminUsers = (
  params: SearchAdminUsersParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageAdminUserResponse>(
    { url: `/admin/users`, method: "GET", params, signal },
    options,
  );
};

export const getSearchAdminUsersQueryKey = (
  params?: SearchAdminUsersParams,
) => {
  return [`/admin/users`, ...(params ? [params] : [])] as const;
};

export const getSearchAdminUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminUsers>>,
  TError = unknown,
>(
  params: SearchAdminUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminUsers>>
  > = ({ signal }) => searchAdminUsers(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminUsers>>
>;
export type SearchAdminUsersQueryError = unknown;

export function useSearchAdminUsers<
  TData = Awaited<ReturnType<typeof searchAdminUsers>>,
  TError = unknown,
>(
  params: SearchAdminUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof searchAdminUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminUsers<
  TData = Awaited<ReturnType<typeof searchAdminUsers>>,
  TError = unknown,
>(
  params: SearchAdminUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof searchAdminUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminUsers<
  TData = Awaited<ReturnType<typeof searchAdminUsers>>,
  TError = unknown,
>(
  params: SearchAdminUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자 목록 조회
 */

export function useSearchAdminUsers<
  TData = Awaited<ReturnType<typeof searchAdminUsers>>,
  TError = unknown,
>(
  params: SearchAdminUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminUsersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
