/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminRecordResponse,
  PageAdminRecordResponse,
  SearchAdminRecordsParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 녹화 취소
 */
export const cancelAdminRecord = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/records/${id}/cancel`, method: "POST", signal },
    options,
  );
};

export const getCancelAdminRecordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelAdminRecord>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelAdminRecord>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["cancelAdminRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelAdminRecord>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return cancelAdminRecord(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelAdminRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelAdminRecord>>
>;

export type CancelAdminRecordMutationError = unknown;

/**
 * @summary 녹화 취소
 */
export const useCancelAdminRecord = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelAdminRecord>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelAdminRecord>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getCancelAdminRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 녹화 기록 조회
 */
export const searchAdminRecords = (
  params: SearchAdminRecordsParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageAdminRecordResponse>(
    { url: `/admin/records`, method: "GET", params, signal },
    options,
  );
};

export const getSearchAdminRecordsQueryKey = (
  params?: SearchAdminRecordsParams,
) => {
  return [`/admin/records`, ...(params ? [params] : [])] as const;
};

export const getSearchAdminRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminRecords>>,
  TError = unknown,
>(
  params: SearchAdminRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecords>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminRecordsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminRecords>>
  > = ({ signal }) => searchAdminRecords(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminRecords>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminRecordsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminRecords>>
>;
export type SearchAdminRecordsQueryError = unknown;

export function useSearchAdminRecords<
  TData = Awaited<ReturnType<typeof searchAdminRecords>>,
  TError = unknown,
>(
  params: SearchAdminRecordsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecords>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminRecords>>,
          TError,
          Awaited<ReturnType<typeof searchAdminRecords>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminRecords<
  TData = Awaited<ReturnType<typeof searchAdminRecords>>,
  TError = unknown,
>(
  params: SearchAdminRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecords>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminRecords>>,
          TError,
          Awaited<ReturnType<typeof searchAdminRecords>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminRecords<
  TData = Awaited<ReturnType<typeof searchAdminRecords>>,
  TError = unknown,
>(
  params: SearchAdminRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecords>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 녹화 기록 조회
 */

export function useSearchAdminRecords<
  TData = Awaited<ReturnType<typeof searchAdminRecords>>,
  TError = unknown,
>(
  params: SearchAdminRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecords>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminRecordsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 녹화 단건 조회
 */
export const getAdminRecordById = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminRecordResponse>(
    { url: `/admin/records/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetAdminRecordByIdQueryKey = (id?: number) => {
  return [`/admin/records/${id}`] as const;
};

export const getGetAdminRecordByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminRecordById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminRecordByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminRecordById>>
  > = ({ signal }) => getAdminRecordById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminRecordById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminRecordByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminRecordById>>
>;
export type GetAdminRecordByIdQueryError = unknown;

export function useGetAdminRecordById<
  TData = Awaited<ReturnType<typeof getAdminRecordById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminRecordById>>,
          TError,
          Awaited<ReturnType<typeof getAdminRecordById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRecordById<
  TData = Awaited<ReturnType<typeof getAdminRecordById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminRecordById>>,
          TError,
          Awaited<ReturnType<typeof getAdminRecordById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRecordById<
  TData = Awaited<ReturnType<typeof getAdminRecordById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 녹화 단건 조회
 */

export function useGetAdminRecordById<
  TData = Awaited<ReturnType<typeof getAdminRecordById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminRecordByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
