/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminChannelCreateRequest,
  AdminChannelResponse,
  AdminChannelUpdateRequest,
  PageAdminChannelResponse,
  SearchAdminChannelsParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 채널 단건 조회
 */
export const getAdminChannelById = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminChannelResponse>(
    { url: `/admin/channels/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetAdminChannelByIdQueryKey = (id?: number) => {
  return [`/admin/channels/${id}`] as const;
};

export const getGetAdminChannelByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminChannelById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminChannelByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminChannelById>>
  > = ({ signal }) => getAdminChannelById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminChannelById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminChannelByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminChannelById>>
>;
export type GetAdminChannelByIdQueryError = unknown;

export function useGetAdminChannelById<
  TData = Awaited<ReturnType<typeof getAdminChannelById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminChannelById>>,
          TError,
          Awaited<ReturnType<typeof getAdminChannelById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminChannelById<
  TData = Awaited<ReturnType<typeof getAdminChannelById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminChannelById>>,
          TError,
          Awaited<ReturnType<typeof getAdminChannelById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminChannelById<
  TData = Awaited<ReturnType<typeof getAdminChannelById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 단건 조회
 */

export function useGetAdminChannelById<
  TData = Awaited<ReturnType<typeof getAdminChannelById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminChannelByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 수정
 */
export const updateAdminChannel = (
  id: number,
  adminChannelUpdateRequest: AdminChannelUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<AdminChannelResponse>(
    {
      url: `/admin/channels/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminChannelUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminChannelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminChannel>>,
    TError,
    { id: number; data: AdminChannelUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminChannel>>,
  TError,
  { id: number; data: AdminChannelUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminChannel"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminChannel>>,
    { id: number; data: AdminChannelUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAdminChannel(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminChannelMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminChannel>>
>;
export type UpdateAdminChannelMutationBody = AdminChannelUpdateRequest;
export type UpdateAdminChannelMutationError = unknown;

/**
 * @summary 채널 수정
 */
export const useUpdateAdminChannel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminChannel>>,
      TError,
      { id: number; data: AdminChannelUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminChannel>>,
  TError,
  { id: number; data: AdminChannelUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateAdminChannelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채널 삭제
 */
export const deleteAdminChannel = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/channels/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteAdminChannelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminChannel>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdminChannel>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAdminChannel"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdminChannel>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAdminChannel(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdminChannelMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminChannel>>
>;

export type DeleteAdminChannelMutationError = unknown;

/**
 * @summary 채널 삭제
 */
export const useDeleteAdminChannel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdminChannel>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdminChannel>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteAdminChannelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채널 목록 조회
 */
export const searchAdminChannels = (
  params: SearchAdminChannelsParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageAdminChannelResponse>(
    { url: `/admin/channels`, method: "GET", params, signal },
    options,
  );
};

export const getSearchAdminChannelsQueryKey = (
  params?: SearchAdminChannelsParams,
) => {
  return [`/admin/channels`, ...(params ? [params] : [])] as const;
};

export const getSearchAdminChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminChannels>>,
  TError = unknown,
>(
  params: SearchAdminChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannels>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminChannelsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminChannels>>
  > = ({ signal }) => searchAdminChannels(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminChannels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminChannels>>
>;
export type SearchAdminChannelsQueryError = unknown;

export function useSearchAdminChannels<
  TData = Awaited<ReturnType<typeof searchAdminChannels>>,
  TError = unknown,
>(
  params: SearchAdminChannelsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannels>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminChannels>>,
          TError,
          Awaited<ReturnType<typeof searchAdminChannels>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminChannels<
  TData = Awaited<ReturnType<typeof searchAdminChannels>>,
  TError = unknown,
>(
  params: SearchAdminChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannels>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminChannels>>,
          TError,
          Awaited<ReturnType<typeof searchAdminChannels>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminChannels<
  TData = Awaited<ReturnType<typeof searchAdminChannels>>,
  TError = unknown,
>(
  params: SearchAdminChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannels>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 목록 조회
 */

export function useSearchAdminChannels<
  TData = Awaited<ReturnType<typeof searchAdminChannels>>,
  TError = unknown,
>(
  params: SearchAdminChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannels>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminChannelsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 생성
 */
export const createAdminChannel = (
  adminChannelCreateRequest: AdminChannelCreateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminChannelResponse>(
    {
      url: `/admin/channels`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: adminChannelCreateRequest,
      signal,
    },
    options,
  );
};

export const getCreateAdminChannelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAdminChannel>>,
    TError,
    { data: AdminChannelCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAdminChannel>>,
  TError,
  { data: AdminChannelCreateRequest },
  TContext
> => {
  const mutationKey = ["createAdminChannel"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAdminChannel>>,
    { data: AdminChannelCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createAdminChannel(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAdminChannelMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAdminChannel>>
>;
export type CreateAdminChannelMutationBody = AdminChannelCreateRequest;
export type CreateAdminChannelMutationError = unknown;

/**
 * @summary 채널 생성
 */
export const useCreateAdminChannel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAdminChannel>>,
      TError,
      { data: AdminChannelCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAdminChannel>>,
  TError,
  { data: AdminChannelCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateAdminChannelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
