/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminRecordScheduleCreateRequest,
  AdminRecordScheduleResponse,
  AdminRecordScheduleUpdateRequest,
  PageAdminRecordScheduleResponse,
  SearchAdminRecordSchedulesParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 녹화 스케줄 단건 조회
 */
export const getAdminRecordScheduleById = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminRecordScheduleResponse>(
    { url: `/admin/record-schedules/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetAdminRecordScheduleByIdQueryKey = (id?: number) => {
  return [`/admin/record-schedules/${id}`] as const;
};

export const getGetAdminRecordScheduleByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminRecordScheduleByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminRecordScheduleById>>
  > = ({ signal }) => getAdminRecordScheduleById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminRecordScheduleByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminRecordScheduleById>>
>;
export type GetAdminRecordScheduleByIdQueryError = unknown;

export function useGetAdminRecordScheduleById<
  TData = Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
          TError,
          Awaited<ReturnType<typeof getAdminRecordScheduleById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRecordScheduleById<
  TData = Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
          TError,
          Awaited<ReturnType<typeof getAdminRecordScheduleById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRecordScheduleById<
  TData = Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 녹화 스케줄 단건 조회
 */

export function useGetAdminRecordScheduleById<
  TData = Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRecordScheduleById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminRecordScheduleByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 녹화 스케줄 수정
 */
export const updateAdminRecordSchedule = (
  id: number,
  adminRecordScheduleUpdateRequest: AdminRecordScheduleUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<AdminRecordScheduleResponse>(
    {
      url: `/admin/record-schedules/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminRecordScheduleUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminRecordScheduleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminRecordSchedule>>,
    TError,
    { id: number; data: AdminRecordScheduleUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminRecordSchedule>>,
  TError,
  { id: number; data: AdminRecordScheduleUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminRecordSchedule"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminRecordSchedule>>,
    { id: number; data: AdminRecordScheduleUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAdminRecordSchedule(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminRecordScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminRecordSchedule>>
>;
export type UpdateAdminRecordScheduleMutationBody =
  AdminRecordScheduleUpdateRequest;
export type UpdateAdminRecordScheduleMutationError = unknown;

/**
 * @summary 녹화 스케줄 수정
 */
export const useUpdateAdminRecordSchedule = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminRecordSchedule>>,
      TError,
      { id: number; data: AdminRecordScheduleUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminRecordSchedule>>,
  TError,
  { id: number; data: AdminRecordScheduleUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateAdminRecordScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 녹화 스케줄 삭제
 */
export const deleteAdminRecordSchedule = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/record-schedules/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteAdminRecordScheduleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminRecordSchedule>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdminRecordSchedule>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAdminRecordSchedule"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdminRecordSchedule>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAdminRecordSchedule(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdminRecordScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminRecordSchedule>>
>;

export type DeleteAdminRecordScheduleMutationError = unknown;

/**
 * @summary 녹화 스케줄 삭제
 */
export const useDeleteAdminRecordSchedule = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdminRecordSchedule>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdminRecordSchedule>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteAdminRecordScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 녹화 스케줄 목록 조회
 */
export const searchAdminRecordSchedules = (
  params: SearchAdminRecordSchedulesParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageAdminRecordScheduleResponse>(
    { url: `/admin/record-schedules`, method: "GET", params, signal },
    options,
  );
};

export const getSearchAdminRecordSchedulesQueryKey = (
  params?: SearchAdminRecordSchedulesParams,
) => {
  return [`/admin/record-schedules`, ...(params ? [params] : [])] as const;
};

export const getSearchAdminRecordSchedulesQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
  TError = unknown,
>(
  params: SearchAdminRecordSchedulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminRecordSchedulesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminRecordSchedules>>
  > = ({ signal }) =>
    searchAdminRecordSchedules(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminRecordSchedulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminRecordSchedules>>
>;
export type SearchAdminRecordSchedulesQueryError = unknown;

export function useSearchAdminRecordSchedules<
  TData = Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
  TError = unknown,
>(
  params: SearchAdminRecordSchedulesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
          TError,
          Awaited<ReturnType<typeof searchAdminRecordSchedules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminRecordSchedules<
  TData = Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
  TError = unknown,
>(
  params: SearchAdminRecordSchedulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
          TError,
          Awaited<ReturnType<typeof searchAdminRecordSchedules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminRecordSchedules<
  TData = Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
  TError = unknown,
>(
  params: SearchAdminRecordSchedulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 녹화 스케줄 목록 조회
 */

export function useSearchAdminRecordSchedules<
  TData = Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
  TError = unknown,
>(
  params: SearchAdminRecordSchedulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminRecordSchedules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminRecordSchedulesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 녹화 스케줄 생성
 */
export const createAdminRecordSchedule = (
  adminRecordScheduleCreateRequest: AdminRecordScheduleCreateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminRecordScheduleResponse>(
    {
      url: `/admin/record-schedules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: adminRecordScheduleCreateRequest,
      signal,
    },
    options,
  );
};

export const getCreateAdminRecordScheduleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAdminRecordSchedule>>,
    TError,
    { data: AdminRecordScheduleCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAdminRecordSchedule>>,
  TError,
  { data: AdminRecordScheduleCreateRequest },
  TContext
> => {
  const mutationKey = ["createAdminRecordSchedule"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAdminRecordSchedule>>,
    { data: AdminRecordScheduleCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createAdminRecordSchedule(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAdminRecordScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAdminRecordSchedule>>
>;
export type CreateAdminRecordScheduleMutationBody =
  AdminRecordScheduleCreateRequest;
export type CreateAdminRecordScheduleMutationError = unknown;

/**
 * @summary 녹화 스케줄 생성
 */
export const useCreateAdminRecordSchedule = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAdminRecordSchedule>>,
      TError,
      { data: AdminRecordScheduleCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAdminRecordSchedule>>,
  TError,
  { data: AdminRecordScheduleCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateAdminRecordScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
