/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminVideoResponse,
  AdminVideoUpdateRequest,
  PageAdminVideoResponse,
  SearchAdminVideosParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 동영상 단건 조회
 */
export const getAdminVideoById = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminVideoResponse>(
    { url: `/admin/videos/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetAdminVideoByIdQueryKey = (id?: number) => {
  return [`/admin/videos/${id}`] as const;
};

export const getGetAdminVideoByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminVideoById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminVideoById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminVideoByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminVideoById>>
  > = ({ signal }) => getAdminVideoById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminVideoById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminVideoByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminVideoById>>
>;
export type GetAdminVideoByIdQueryError = unknown;

export function useGetAdminVideoById<
  TData = Awaited<ReturnType<typeof getAdminVideoById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminVideoById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminVideoById>>,
          TError,
          Awaited<ReturnType<typeof getAdminVideoById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminVideoById<
  TData = Awaited<ReturnType<typeof getAdminVideoById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminVideoById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminVideoById>>,
          TError,
          Awaited<ReturnType<typeof getAdminVideoById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminVideoById<
  TData = Awaited<ReturnType<typeof getAdminVideoById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminVideoById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 단건 조회
 */

export function useGetAdminVideoById<
  TData = Awaited<ReturnType<typeof getAdminVideoById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminVideoById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminVideoByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 동영상 수정
 */
export const updateAdminVideo = (
  id: number,
  adminVideoUpdateRequest: AdminVideoUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<AdminVideoResponse>(
    {
      url: `/admin/videos/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminVideoUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminVideoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminVideo>>,
    TError,
    { id: number; data: AdminVideoUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminVideo>>,
  TError,
  { id: number; data: AdminVideoUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminVideo>>,
    { id: number; data: AdminVideoUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAdminVideo(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminVideo>>
>;
export type UpdateAdminVideoMutationBody = AdminVideoUpdateRequest;
export type UpdateAdminVideoMutationError = unknown;

/**
 * @summary 동영상 수정
 */
export const useUpdateAdminVideo = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminVideo>>,
      TError,
      { id: number; data: AdminVideoUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminVideo>>,
  TError,
  { id: number; data: AdminVideoUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateAdminVideoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 동영상 삭제
 */
export const deleteAdminVideo = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/videos/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteAdminVideoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdminVideo>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAdminVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdminVideo>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAdminVideo(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdminVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminVideo>>
>;

export type DeleteAdminVideoMutationError = unknown;

/**
 * @summary 동영상 삭제
 */
export const useDeleteAdminVideo = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdminVideo>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdminVideo>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteAdminVideoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 동영상 목록 조회
 */
export const searchAdminVideos = (
  params: SearchAdminVideosParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageAdminVideoResponse>(
    { url: `/admin/videos`, method: "GET", params, signal },
    options,
  );
};

export const getSearchAdminVideosQueryKey = (
  params?: SearchAdminVideosParams,
) => {
  return [`/admin/videos`, ...(params ? [params] : [])] as const;
};

export const getSearchAdminVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminVideos>>,
  TError = unknown,
>(
  params: SearchAdminVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminVideosQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminVideos>>
  > = ({ signal }) => searchAdminVideos(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminVideos>>
>;
export type SearchAdminVideosQueryError = unknown;

export function useSearchAdminVideos<
  TData = Awaited<ReturnType<typeof searchAdminVideos>>,
  TError = unknown,
>(
  params: SearchAdminVideosParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminVideos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminVideos>>,
          TError,
          Awaited<ReturnType<typeof searchAdminVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminVideos<
  TData = Awaited<ReturnType<typeof searchAdminVideos>>,
  TError = unknown,
>(
  params: SearchAdminVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminVideos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminVideos>>,
          TError,
          Awaited<ReturnType<typeof searchAdminVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminVideos<
  TData = Awaited<ReturnType<typeof searchAdminVideos>>,
  TError = unknown,
>(
  params: SearchAdminVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 목록 조회
 */

export function useSearchAdminVideos<
  TData = Awaited<ReturnType<typeof searchAdminVideos>>,
  TError = unknown,
>(
  params: SearchAdminVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
