/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminRecordSearchRequestPlatformType } from "./adminRecordSearchRequestPlatformType";

export interface AdminRecordSearchRequest {
  id?: number;
  channelName?: string;
  title?: string;
  platformStreamId?: string;
  platformType?: AdminRecordSearchRequestPlatformType;
  isEnded?: boolean;
  isCancelled?: boolean;
  createdAtFrom?: string;
  createdAtTo?: string;
}
