/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminRecordScheduleUpdateRequestPlatformType } from "./adminRecordScheduleUpdateRequestPlatformType";
import type { AdminRecordScheduleUpdateRequestScheduleType } from "./adminRecordScheduleUpdateRequestScheduleType";
import type { AdminRecordScheduleUpdateRequestRecordQuality } from "./adminRecordScheduleUpdateRequestRecordQuality";

export interface AdminRecordScheduleUpdateRequest {
  platformType?: AdminRecordScheduleUpdateRequestPlatformType;
  scheduleType?: AdminRecordScheduleUpdateRequestScheduleType;
  value?: string;
  recordQuality?: AdminRecordScheduleUpdateRequestRecordQuality;
  priority?: number;
}
