/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminRecordScheduleResponsePlatformType } from "./adminRecordScheduleResponsePlatformType";
import type { AdminRecordScheduleResponseScheduleType } from "./adminRecordScheduleResponseScheduleType";
import type { AdminRecordScheduleResponseRecordQuality } from "./adminRecordScheduleResponseRecordQuality";

export interface AdminRecordScheduleResponse {
  id: number;
  channelId: number;
  platformType: AdminRecordScheduleResponsePlatformType;
  scheduleType: AdminRecordScheduleResponseScheduleType;
  value: string;
  recordQuality: AdminRecordScheduleResponseRecordQuality;
  priority: number;
  createdAt: string;
  updatedAt: string;
}
