/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminVideoSearchRequestContentPrivacy } from "./adminVideoSearchRequestContentPrivacy";

export interface AdminVideoSearchRequest {
  title?: string;
  channelName?: string;
  contentPrivacy?: AdminVideoSearchRequestContentPrivacy;
  createdAtFrom?: string;
  createdAtTo?: string;
}
