/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminChannelResponseContentPrivacy } from "./adminChannelResponseContentPrivacy";

export interface AdminChannelResponse {
  id: number;
  uuid: string;
  name: string;
  profileUrl: string;
  contentPrivacy: AdminChannelResponseContentPrivacy;
  createdAt: string;
  updatedAt: string;
}
