/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { AdminVideoResponseContentPrivacy } from "./adminVideoResponseContentPrivacy";
import type { RecordInfo } from "./recordInfo";

export interface AdminVideoResponse {
  id: number;
  uuid: string;
  channel: ChannelInfo;
  title: string;
  duration: number;
  fileSize: number;
  thumbnailUrl: string;
  playlistUrl: string;
  contentPrivacy: AdminVideoResponseContentPrivacy;
  createdAt: string;
  updatedAt: string;
  record?: RecordInfo;
}
