/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminChannelPlatformResponsePlatformType } from "./adminChannelPlatformResponsePlatformType";

export interface AdminChannelPlatformResponse {
  id: number;
  channelId: number;
  platformType: AdminChannelPlatformResponsePlatformType;
  platformChannelId: string;
  isSyncProfile: boolean;
  createdAt: string;
  updatedAt: string;
}
