/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserResponseRole } from "./adminUserResponseRole";

export interface AdminUserResponse {
  id: number;
  uuid: string;
  username: string;
  name: string;
  email: string;
  role: AdminUserResponseRole;
  lastLoginAt?: string;
  createdAt: string;
  updatedAt: string;
}
