/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 로그인 요청
 */
export interface AuthLoginRequest {
  /** 아이디 */
  username: string;
  /** 비밀번호 */
  password: string;
}
