/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 토큰 갱신 요청
 */
export interface AuthTokenRefreshRequest {
  /** 리프레시 토큰 (쿠키에 없을 때만 사용) */
  refreshToken?: string;
}
