/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { Keyword } from "./keyword";

/**
 * 구간 채팅 분석
 */
export interface Bucket {
  /** 구간 시작 오프셋 (밀리초) */
  offsetMillis: number;
  /** 구간 채팅 개수 */
  count: number;
  /** 구간 대표 키워드 (피크 구간에만 채워진다) */
  keywords: Keyword[];
}
