/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelAdminUpdateRequestContentPrivacy } from "./channelAdminUpdateRequestContentPrivacy";

/**
 * 채널 수정 요청 (관리자)
 */
export interface ChannelAdminUpdateRequest {
  /** 채널 이름 */
  name?: string;
  /** 콘텐츠 공개 범위 (PUBLIC/UNLISTED/PRIVATE) */
  contentPrivacy?: ChannelAdminUpdateRequestContentPrivacy;
}
