/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelPlatformAdminCreateRequestPlatformType } from "./channelPlatformAdminCreateRequestPlatformType";

/**
 * 채널 플랫폼 생성 요청 (관리자)
 */
export interface ChannelPlatformAdminCreateRequest {
  /** 채널 ID */
  channelId: number;
  /** 플랫폼 유형 (CHZZK/TWITCH/SOOP/YOUTUBE) */
  platformType: ChannelPlatformAdminCreateRequestPlatformType;
  /** 플랫폼 채널 ID */
  platformChannelId: string;
  /** 프로필 동기화 여부 */
  isSyncProfile: boolean;
}
