/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelPlatformSearchResponsePlatformType } from "./channelPlatformSearchResponsePlatformType";

/**
 * 채널 플랫폼 목록 응답 (공개)
 */
export interface ChannelPlatformSearchResponse {
  /** 플랫폼 유형 (CHZZK/TWITCH/SOOP/YOUTUBE) */
  platformType: ChannelPlatformSearchResponsePlatformType;
  /** 플랫폼 채널 ID */
  platformChannelId: string;
  /** 방송 URL */
  streamUrl: string;
  /** 프로필 동기화 여부 */
  isSyncProfile: boolean;
}
