/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelPlatformAdminSearchRequestPlatformType } from "./channelPlatformAdminSearchRequestPlatformType";

/**
 * 채널 플랫폼 검색 요청 (관리자)
 */
export interface ChannelPlatformAdminSearchRequest {
  /** 채널 플랫폼 ID */
  id?: number;
  /** 채널 이름 */
  channelName?: string;
  /** 플랫폼 유형 (CHZZK/TWITCH/SOOP/YOUTUBE) */
  platformType?: ChannelPlatformAdminSearchRequestPlatformType;
  /** 플랫폼 채널 ID */
  platformChannelId?: string;
  /** 프로필 동기화 여부 */
  isSyncProfile?: boolean;
}
