/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 채널 플랫폼 수정 요청 (관리자)
 */
export interface ChannelPlatformAdminUpdateRequest {
  /** 플랫폼 채널 ID */
  platformChannelId?: string;
  /** 프로필 동기화 여부 */
  isSyncProfile?: boolean;
}
