/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 채널 통계 응답
 */
export interface ChannelStatsResponse {
  /** 동영상 수 */
  videoCount: number;
  /** 전체 파일 크기 (바이트) */
  totalFileSize: number;
}
