/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelGetResponseContentPrivacy } from "./channelGetResponseContentPrivacy";

/**
 * 채널 단건 응답 (공개)
 */
export interface ChannelGetResponse {
  /** 채널 UUID */
  uuid: string;
  /** 채널 이름 */
  name: string;
  /** 프로필 이미지 URL */
  profileUrl: string;
  /** 콘텐츠 공개 범위 (PUBLIC/UNLISTED/PRIVATE) */
  contentPrivacy: ChannelGetResponseContentPrivacy;
  /** 생성 일시 */
  createdAt: string;
  /** 수정 일시 */
  updatedAt: string;
}
