/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelAdminSearchRequestContentPrivacy } from "./channelAdminSearchRequestContentPrivacy";

/**
 * 채널 검색 요청 (관리자)
 */
export interface ChannelAdminSearchRequest {
  /** 채널 ID */
  id?: number;
  /** 채널 UUID */
  uuid?: string;
  /** 채널 이름 */
  name?: string;
  /** 콘텐츠 공개 범위 (PUBLIC/UNLISTED/PRIVATE) */
  contentPrivacy?: ChannelAdminSearchRequestContentPrivacy;
}
