/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { ChannelPlatformAdminUpdateResponsePlatformType } from "./channelPlatformAdminUpdateResponsePlatformType";

/**
 * 채널 플랫폼 수정 응답 (관리자)
 */
export interface ChannelPlatformAdminUpdateResponse {
  /** 채널 플랫폼 ID */
  id: number;
  channel: ChannelInfo;
  /** 플랫폼 유형 (CHZZK/TWITCH/SOOP/YOUTUBE) */
  platformType: ChannelPlatformAdminUpdateResponsePlatformType;
  /** 플랫폼 채널 ID */
  platformChannelId: string;
  /** 플랫폼 방송 URL */
  platformUrl: string;
  /** 프로필 동기화 여부 */
  isSyncProfile: boolean;
  /** 생성 일시 */
  createdAt: string;
  /** 수정 일시 */
  updatedAt: string;
}
