/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 대시보드 통계 응답 (관리자)
 */
export interface DashboardStatResponse {
  /** 전체 채널 수 */
  totalChannels: number;
  /** 전체 동영상 수 */
  totalVideos: number;
  /** 전체 재생 시간 (초) */
  totalDuration: number;
  /** 전체 스토리지 사용량 (바이트) */
  totalStorage: number;
}
