/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 구간 대표 키워드
 */
export interface Keyword {
  /** 키워드 */
  keyword: string;
  /** 구간 내 등장 횟수 */
  count: number;
  /** 키워드 대표 채팅 원문 */
  label: string;
}
