/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicVideoResponse } from "./publicVideoResponse";
import type { SortObject } from "./sortObject";
import type { PageableObject } from "./pageableObject";

export interface PagePublicVideoResponse {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: PublicVideoResponse[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}
