/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { PageableObject } from "./pageableObject";
import type { PublicChannelResponse } from "./publicChannelResponse";
import type { SortObject } from "./sortObject";

export interface PagePublicChannelResponse {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  content?: PublicChannelResponse[];
  number?: number;
  sort?: SortObject;
  empty?: boolean;
}
