/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformResponsePlatformType } from "./platformResponsePlatformType";

/**
 * 플랫폼 연동 정보
 */
export interface PlatformResponse {
  /** 플랫폼 연동 ID */
  id: number;
  /** 플랫폼 유형 (CHZZK/TWITCH/SOOP/YOUTUBE) */
  platformType: PlatformResponsePlatformType;
  /** 플랫폼 채널 ID */
  platformChannelId: string;
  /** 플랫폼 URL */
  platformUrl: string;
  /** 프로필 동기화 여부 */
  isSyncProfile: boolean;
}
