/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 플랫폼 채널 조회 요청 (관리자)
 */
export interface PlatformAdminChannelResolveRequest {
  /** 플랫폼 채널 URL */
  url: string;
}
