/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformAdminChannelResolveResponsePlatformType } from "./platformAdminChannelResolveResponsePlatformType";

/**
 * 플랫폼 채널 조회 응답 (관리자)
 */
export interface PlatformAdminChannelResolveResponse {
  /** 플랫폼 유형 (CHZZK/TWITCH/SOOP/YOUTUBE) */
  platformType: PlatformAdminChannelResolveResponsePlatformType;
  /** 플랫폼 채널 ID */
  platformChannelId: string;
  /** 채널 이름 */
  name: string;
  /** 프로필 썸네일 URL */
  thumbnailUrl?: string;
}
