/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { VideoInfo } from "./videoInfo";
import type { RecordAdminSearchResponsePlatformType } from "./recordAdminSearchResponsePlatformType";

/**
 * 녹화 기록 목록 응답 (관리자)
 */
export interface RecordAdminSearchResponse {
  /** 녹화 기록 ID */
  id: number;
  channel: ChannelInfo;
  video: VideoInfo;
  /** 플랫폼 유형 (CHZZK/SOOP/TWITCH/YOUTUBE) */
  platformType: RecordAdminSearchResponsePlatformType;
  /** 플랫폼 스트림 ID */
  platformStreamId: string;
  /** 녹화 화질 */
  recordQuality: string;
  /** 종료 여부 */
  isEnded: boolean;
  /** 취소 여부 */
  isCancelled: boolean;
  /** 녹화 시작 일시 */
  createdAt: string;
  /** 녹화 종료 일시 */
  endedAt?: string;
}
