/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecordScheduleAdminSearchRequestPlatformType } from "./recordScheduleAdminSearchRequestPlatformType";
import type { RecordScheduleAdminSearchRequestScheduleType } from "./recordScheduleAdminSearchRequestScheduleType";
import type { RecordScheduleAdminSearchRequestRecordQuality } from "./recordScheduleAdminSearchRequestRecordQuality";

/**
 * 녹화 스케줄 검색 요청 (관리자)
 */
export interface RecordScheduleAdminSearchRequest {
  /** 녹화 스케줄 ID */
  id?: number;
  /** 채널 이름 */
  channelName?: string;
  /** 플랫폼 유형 (CHZZK/SOOP/TWITCH/YOUTUBE) */
  platformType?: RecordScheduleAdminSearchRequestPlatformType;
  /** 녹화 스케줄 유형 (ONCE/ALWAYS/WEEKLY/SPECIFIC) */
  scheduleType?: RecordScheduleAdminSearchRequestScheduleType;
  /** 녹화 화질 */
  recordQuality?: RecordScheduleAdminSearchRequestRecordQuality;
}
