/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecordScheduleAdminCreateRequestPlatformType } from "./recordScheduleAdminCreateRequestPlatformType";
import type { RecordScheduleAdminCreateRequestScheduleType } from "./recordScheduleAdminCreateRequestScheduleType";
import type { RecordScheduleAdminCreateRequestRecordQuality } from "./recordScheduleAdminCreateRequestRecordQuality";

/**
 * 녹화 스케줄 생성 요청 (관리자)
 */
export interface RecordScheduleAdminCreateRequest {
  /** 채널 ID */
  channelId: number;
  /** 플랫폼 유형 (CHZZK/SOOP/TWITCH/YOUTUBE) */
  platformType: RecordScheduleAdminCreateRequestPlatformType;
  /** 녹화 스케줄 유형 (ONCE/ALWAYS/WEEKLY/SPECIFIC) */
  scheduleType: RecordScheduleAdminCreateRequestScheduleType;
  /** 스케줄 값 */
  value: string;
  /** 녹화 화질 */
  recordQuality: RecordScheduleAdminCreateRequestRecordQuality;
  /** 우선순위 */
  priority: number;
  /** 자동 소장 여부 */
  autoArchive: boolean;
}
