/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecordInfoPlatformType } from "./recordInfoPlatformType";

export interface RecordInfo {
  platformType: RecordInfoPlatformType;
  platformStreamId: string;
  recordQuality: string;
  isEnded: boolean;
  isCancelled: boolean;
  startedAt: string;
  endedAt?: string;
}
