/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { RecordScheduleAdminCreateResponsePlatformType } from "./recordScheduleAdminCreateResponsePlatformType";
import type { RecordScheduleAdminCreateResponseScheduleType } from "./recordScheduleAdminCreateResponseScheduleType";
import type { RecordScheduleAdminCreateResponseRecordQuality } from "./recordScheduleAdminCreateResponseRecordQuality";

/**
 * 녹화 스케줄 생성 응답 (관리자)
 */
export interface RecordScheduleAdminCreateResponse {
  /** 녹화 스케줄 ID */
  id: number;
  channel: ChannelInfo;
  /** 플랫폼 유형 (CHZZK/SOOP/TWITCH/YOUTUBE) */
  platformType: RecordScheduleAdminCreateResponsePlatformType;
  /** 녹화 스케줄 유형 (ONCE/ALWAYS/WEEKLY/SPECIFIC) */
  scheduleType: RecordScheduleAdminCreateResponseScheduleType;
  /** 스케줄 값 */
  value: string;
  /** 녹화 화질 */
  recordQuality: RecordScheduleAdminCreateResponseRecordQuality;
  /** 우선순위 */
  priority: number;
  /** 자동 소장 여부 */
  autoArchive: boolean;
  /** 생성 일시 */
  createdAt: string;
  /** 수정 일시 */
  updatedAt: string;
}
