/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecordAdminSearchRequestPlatformType } from "./recordAdminSearchRequestPlatformType";

/**
 * 녹화 기록 검색 요청 (관리자)
 */
export interface RecordAdminSearchRequest {
  /** 녹화 기록 ID */
  id?: number;
  /** 채널 이름 */
  channelName?: string;
  /** 제목 */
  title?: string;
  /** 플랫폼 스트림 ID */
  platformStreamId?: string;
  /** 플랫폼 유형 (CHZZK/SOOP/TWITCH/YOUTUBE) */
  platformType?: RecordAdminSearchRequestPlatformType;
  /** 종료 여부 */
  isEnded?: boolean;
  /** 취소 여부 */
  isCancelled?: boolean;
  /** 생성 일시 시작 */
  createdAtFrom?: string;
  /** 생성 일시 끝 */
  createdAtTo?: string;
}
