/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleResponseScheduleType } from "./scheduleResponseScheduleType";
import type { ScheduleResponseRecordQuality } from "./scheduleResponseRecordQuality";

/**
 * 녹화 스케줄 정보
 */
export interface ScheduleResponse {
  /** 스케줄 ID */
  id: number;
  /** 녹화 스케줄 유형 (ONCE/ALWAYS/N_DAYS_OF_EVERY_WEEK/SPECIFIC_DAY) */
  scheduleType: ScheduleResponseScheduleType;
  /** 스케줄 값 */
  value: string;
  /** 녹화 화질 */
  recordQuality: ScheduleResponseRecordQuality;
  /** 우선순위 */
  priority: number;
  /** 자동 소장 여부 */
  autoArchive: boolean;
}
