/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleRequestScheduleType } from "./scheduleRequestScheduleType";
import type { ScheduleRequestRecordQuality } from "./scheduleRequestRecordQuality";

/**
 * 녹화 스케줄 요청
 */
export interface ScheduleRequest {
  /** 녹화 스케줄 유형 (ONCE/ALWAYS/N_DAYS_OF_EVERY_WEEK/SPECIFIC_DAY) */
  scheduleType: ScheduleRequestScheduleType;
  /** 스케줄 값 (요일·날짜 JSON 배열, ONCE/ALWAYS는 빈 값) */
  value: string;
  /** 녹화 화질 */
  recordQuality: ScheduleRequestRecordQuality;
  /** 우선순위 */
  priority: number;
  /** 자동 소장 여부 */
  autoArchive: boolean;
}
