/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserSearchRequest } from "./adminUserSearchRequest";
import type { Pageable } from "./pageable";

export type SearchAdminUsersParams = {
  request: AdminUserSearchRequest;
  pageable: Pageable;
};
