/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { UserGetResponseRole } from "./userGetResponseRole";

/**
 * 내 정보 조회 응답
 */
export interface UserGetResponse {
  /** 사용자 ID */
  id: number;
  /** 사용자 UUID */
  uuid: string;
  /** 아이디 */
  username: string;
  /** 이름 */
  name: string;
  /** 역할 (ADMIN/USER) */
  role: UserGetResponseRole;
}
