/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 역할 (ADMIN/USER)
 */
export type UserAdminUpdateResponseRole =
  (typeof UserAdminUpdateResponseRole)[keyof typeof UserAdminUpdateResponseRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserAdminUpdateResponseRole = {
  ADMIN: "ADMIN",
  USER: "USER",
} as const;
