/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { UserAdminUpdateRequestRole } from "./userAdminUpdateRequestRole";

/**
 * 사용자 수정 요청
 */
export interface UserAdminUpdateRequest {
  /** 이름 */
  name?: string;
  /** 역할 (ADMIN/USER) */
  role?: UserAdminUpdateRequestRole;
}
