/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { UserAdminSearchRequestRole } from "./userAdminSearchRequestRole";

/**
 * 사용자 검색 요청
 */
export interface UserAdminSearchRequest {
  /** 사용자 ID */
  id?: number;
  /** 아이디 */
  username?: string;
  /** 이름 */
  name?: string;
  /** 역할 (ADMIN/USER) */
  role?: UserAdminSearchRequestRole;
  /** 가입 일시 시작 */
  createdAtFrom?: string;
  /** 가입 일시 끝 */
  createdAtTo?: string;
}
