/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 자동 삭제 정책 조회 응답 (관리자)
 */
export interface VideoAutoDeletePolicyGetResponse {
  /** 채널 ID (null이면 전체 기본 정책) */
  channelId?: number;
  /** 정책 설정 여부 (false면 아직 설정한 적 없음) */
  isConfigured: boolean;
  /** 자동 삭제 활성화 여부 */
  isEnabled: boolean;
  /** 생성 후 며칠 지난 동영상을 삭제할지 */
  deleteAfterDays?: number;
}
