/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { VideoAdminUpdateRequestContentPrivacy } from "./videoAdminUpdateRequestContentPrivacy";

/**
 * 동영상 수정 요청 (관리자)
 */
export interface VideoAdminUpdateRequest {
  /** 제목 */
  title?: string;
  /** 설명 */
  description?: string;
  /** 콘텐츠 공개 범위 (PUBLIC/UNLISTED/PRIVATE) */
  contentPrivacy?: VideoAdminUpdateRequestContentPrivacy;
  /** 채팅 싱크 오프셋 (밀리초) */
  chatSyncOffsetMillis?: number;
}
