/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 채팅 이모지 응답
 */
export interface VideoChatEmojiSearchResponse {
  /** 메시지 placeholder */
  placeholder: string;
  /** 이모지 파일명 */
  filename: string;
  /** 이모지 이미지 URL */
  imageUrl: string;
}
