/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 자동 삭제 미리보기 요약 응답 (관리자)
 */
export interface VideoAutoDeletePreviewSummaryResponse {
  /** 채널 ID (null이면 전체) */
  channelId?: number;
  /** 다음 자동 삭제 대상 동영상 수 */
  targetCount: number;
  /** 다음 자동 삭제 대상 총 파일 크기 (바이트) */
  totalFileSize: number;
}
