/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 채널별 동영상 자동 삭제 정책 목록 응답 (관리자)
 */
export interface VideoAutoDeleteChannelPolicySearchResponse {
  /** 채널 ID */
  channelId: number;
  /** 자동 삭제 활성화 여부 */
  isEnabled: boolean;
  /** 생성 후 며칠 지난 동영상을 삭제할지 */
  deleteAfterDays: number;
}
