/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 자동 삭제 이력 조회 응답 (관리자)
 */
export interface VideoAutoDeleteHistorySearchResponse {
  /** 이력 ID */
  id: number;
  /** 동영상 ID */
  videoId: number;
  /** 채널 ID */
  channelId: number;
  /** 채널 이름 */
  channelName: string;
  /** 삭제 시점 제목 */
  title: string;
  /** 삭제 시점 파일 크기 (바이트) */
  fileSize: number;
  /** 동영상 생성 일시 */
  videoCreatedAt: string;
  /** 삭제 일시 */
  deletedAt: string;
}
