/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 자동 삭제 미리보기 목록 응답 (관리자)
 */
export interface VideoAutoDeletePreviewResponse {
  /** 동영상 ID */
  id: number;
  /** 동영상 UUID */
  uuid: string;
  /** 채널 ID */
  channelId: number;
  /** 채널 이름 */
  channelName: string;
  /** 제목 */
  title: string;
  /** 파일 크기 (바이트) */
  fileSize: number;
  /** 썸네일 URL */
  thumbnailUrl: string;
  /** 생성 일시 */
  createdAt: string;
  /** 생성 후 경과 일수 */
  ageDays: number;
  /** 보관 기준을 초과한 일수 */
  overDays: number;
}
