/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 자동 삭제 즉시 실행 응답 (관리자)
 */
export interface VideoAutoDeleteRunResponse {
  /** 삭제한 동영상 수 */
  deletedCount: number;
}
