/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 소장 여부 설정 요청 (관리자)
 */
export interface VideoAdminArchiveRequest {
  /** 소장 여부 */
  isArchived: boolean;
}
