/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { RecordInfo } from "./recordInfo";

/**
 * 동영상 단건 응답 (공개)
 */
export interface VideoGetResponse {
  /** 동영상 UUID */
  uuid: string;
  channel: ChannelInfo;
  /** 제목 */
  title: string;
  /** 설명 */
  description?: string;
  /** 재생 시간 (초) */
  duration: number;
  /** 파일 크기 (바이트) */
  fileSize: number;
  /** 썸네일 URL */
  thumbnailUrl: string;
  /** HLS 플레이리스트 URL */
  playlistUrl: string;
  /** 채팅 싱크 오프셋 (밀리초) */
  chatSyncOffsetMillis: number;
  /** 소장 여부 */
  isArchived: boolean;
  /** 최고 시청자 수 */
  peakViewerCount?: number;
  /** 최고 시청자 수 시점의 동영상 시작 기준 오프셋 (밀리초) */
  peakViewerOffsetMillis?: number;
  /** 생성 일시 */
  createdAt: string;
  record?: RecordInfo;
}
