/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { VideoAdminSearchResponseContentPrivacy } from "./videoAdminSearchResponseContentPrivacy";
import type { RecordInfo } from "./recordInfo";

/**
 * 동영상 목록 응답 (관리자)
 */
export interface VideoAdminSearchResponse {
  /** 동영상 ID */
  id: number;
  /** 동영상 UUID */
  uuid: string;
  channel: ChannelInfo;
  /** 제목 */
  title: string;
  /** 설명 */
  description?: string;
  /** 재생 시간 (초) */
  duration: number;
  /** 파일 크기 (바이트) */
  fileSize: number;
  /** 썸네일 URL */
  thumbnailUrl: string;
  /** HLS 플레이리스트 URL */
  playlistUrl: string;
  /** 콘텐츠 공개 범위 (PUBLIC/UNLISTED/PRIVATE) */
  contentPrivacy: VideoAdminSearchResponseContentPrivacy;
  /** 채팅 싱크 오프셋 (밀리초) */
  chatSyncOffsetMillis: number;
  /** 소장 여부 */
  isArchived: boolean;
  /** 소장 처리 일시 */
  archivedAt?: string;
  /** 소장 처리한 사용자 ID */
  archivedBy?: number;
  /** 소장 처리 시 IP */
  archivedIp?: string;
  /** 생성 일시 */
  createdAt: string;
  /** 수정 일시 */
  updatedAt: string;
  record?: RecordInfo;
}
