/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 시청자 수 이력 응답
 */
export interface VideoViewerHistoryGetResponse {
  /** 시청자 수 */
  viewerCount: number;
  /** 동영상 시작 기준 오프셋 (밀리초) */
  offsetMillis: number;
}
