/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 검색 요청 (공개)
 */
export interface VideoSearchRequest {
  /** 제목 */
  title?: string;
  /** 설명 */
  description?: string;
  /** 채널 이름 */
  channelName?: string;
  /** 채널 UUID */
  channelUuid?: string;
}
