/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { VideoAdminSearchRequestContentPrivacy } from "./videoAdminSearchRequestContentPrivacy";

/**
 * 동영상 검색 요청 (관리자)
 */
export interface VideoAdminSearchRequest {
  /** 동영상 ID */
  id?: number;
  /** 동영상 UUID */
  uuid?: string;
  /** 제목 */
  title?: string;
  /** 설명 */
  description?: string;
  /** 채널 이름 */
  channelName?: string;
  /** 콘텐츠 공개 범위 (PUBLIC/UNLISTED/PRIVATE) */
  contentPrivacy?: VideoAdminSearchRequestContentPrivacy;
  /** 소장 여부 */
  isArchived?: boolean;
  /** 생성 일시 시작 */
  createdAtFrom?: string;
  /** 생성 일시 끝 */
  createdAtTo?: string;
}
