/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 챕터 응답
 */
export interface VideoChapterGetResponse {
  /** 동영상 시작 기준 오프셋 (밀리초) */
  offsetMillis: number;
  /** 카테고리 */
  category?: string;
  /** 챕터 시작 시점의 제목 */
  title?: string;
}
