/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 동영상 정보
 */
export interface VideoInfo {
  uuid: string;
  title: string;
  thumbnailUrl: string;
  duration: number;
}
