/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { Bucket } from "./bucket";

/**
 * 동영상 채팅 분석 응답
 */
export interface VideoChatAnalysisGetResponse {
  /** 구간 길이 (밀리초) */
  bucketMillis: number;
  /** 구간별 채팅 분석 목록 */
  buckets: Bucket[];
}
