/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { VideoInfo } from "./videoInfo";

export interface WatchHistoryListResponse {
  channel: ChannelInfo;
  video: VideoInfo;
  lastPosition: number;
  progress: number;
  watchedAt: string;
}
