/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 개별 동영상 시청 기록 응답
 */
export interface WatchHistoryGetResponse {
  /** 마지막 재생 위치 (초) */
  lastPosition: number;
  /** 시청 일시 */
  watchedAt: string;
}
