/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 시청 위치 저장 요청
 */
export interface WatchHistorySaveRequest {
  /** 재생 위치 (초) */
  position: number;
}
