/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelInfo } from "./channelInfo";
import type { VideoInfo } from "./videoInfo";

/**
 * 시청 기록 목록 응답
 */
export interface WatchHistorySearchResponse {
  channel: ChannelInfo;
  video: VideoInfo;
  /** 마지막 재생 위치 (초) */
  lastPosition: number;
  /** 진행률 (%) */
  progress: number;
  /** 시청 일시 */
  watchedAt: string;
}
