/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminDashboardStatsResponse,
  AdminDashboardVideoHistoriesResponse,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 동영상 히스토리 조회
 */
export const getAdminDashboardVideoHistories = (
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminDashboardVideoHistoriesResponse>(
    { url: `/admin/dashboard/video-histories`, method: "GET", signal },
    options,
  );
};

export const getGetAdminDashboardVideoHistoriesQueryKey = () => {
  return [`/admin/dashboard/video-histories`] as const;
};

export const getGetAdminDashboardVideoHistoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminDashboardVideoHistoriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>
  > = ({ signal }) => getAdminDashboardVideoHistories(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminDashboardVideoHistoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>
>;
export type GetAdminDashboardVideoHistoriesQueryError = unknown;

export function useGetAdminDashboardVideoHistories<
  TData = Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
          TError,
          Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminDashboardVideoHistories<
  TData = Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
          TError,
          Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminDashboardVideoHistories<
  TData = Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 동영상 히스토리 조회
 */

export function useGetAdminDashboardVideoHistories<
  TData = Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardVideoHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminDashboardVideoHistoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 대시보드 통계 조회
 */
export const getAdminDashboardStats = (
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminDashboardStatsResponse>(
    { url: `/admin/dashboard/stats`, method: "GET", signal },
    options,
  );
};

export const getGetAdminDashboardStatsQueryKey = () => {
  return [`/admin/dashboard/stats`] as const;
};

export const getGetAdminDashboardStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminDashboardStats>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAdminDashboardStats>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminDashboardStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminDashboardStats>>
  > = ({ signal }) => getAdminDashboardStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminDashboardStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminDashboardStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminDashboardStats>>
>;
export type GetAdminDashboardStatsQueryError = unknown;

export function useGetAdminDashboardStats<
  TData = Awaited<ReturnType<typeof getAdminDashboardStats>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardStats>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDashboardStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminDashboardStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminDashboardStats<
  TData = Awaited<ReturnType<typeof getAdminDashboardStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardStats>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDashboardStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminDashboardStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminDashboardStats<
  TData = Awaited<ReturnType<typeof getAdminDashboardStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardStats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 대시보드 통계 조회
 */

export function useGetAdminDashboardStats<
  TData = Awaited<ReturnType<typeof getAdminDashboardStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminDashboardStats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminDashboardStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
