/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChannelPlatformResponse,
  ChannelStatsResponse,
  PagePublicChannelResponse,
  PublicChannelResponse,
  SearchChannelsParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 채널 목록 조회
 */
export const searchChannels = (
  params: SearchChannelsParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PagePublicChannelResponse>(
    { url: `/channels`, method: "GET", params, signal },
    options,
  );
};

export const getSearchChannelsQueryKey = (params?: SearchChannelsParams) => {
  return [`/channels`, ...(params ? [params] : [])] as const;
};

export const getSearchChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchChannels>>,
  TError = unknown,
>(
  params: SearchChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchChannelsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchChannels>>> = ({
    signal,
  }) => searchChannels(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchChannels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchChannels>>
>;
export type SearchChannelsQueryError = unknown;

export function useSearchChannels<
  TData = Awaited<ReturnType<typeof searchChannels>>,
  TError = unknown,
>(
  params: SearchChannelsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchChannels>>,
          TError,
          Awaited<ReturnType<typeof searchChannels>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchChannels<
  TData = Awaited<ReturnType<typeof searchChannels>>,
  TError = unknown,
>(
  params: SearchChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchChannels>>,
          TError,
          Awaited<ReturnType<typeof searchChannels>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchChannels<
  TData = Awaited<ReturnType<typeof searchChannels>>,
  TError = unknown,
>(
  params: SearchChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 목록 조회
 */

export function useSearchChannels<
  TData = Awaited<ReturnType<typeof searchChannels>>,
  TError = unknown,
>(
  params: SearchChannelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchChannelsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 단건 조회
 */
export const getChannelByUuid = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PublicChannelResponse>(
    { url: `/channels/${uuid}`, method: "GET", signal },
    options,
  );
};

export const getGetChannelByUuidQueryKey = (uuid?: string) => {
  return [`/channels/${uuid}`] as const;
};

export const getGetChannelByUuidQueryOptions = <
  TData = Awaited<ReturnType<typeof getChannelByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelByUuid>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChannelByUuidQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChannelByUuid>>
  > = ({ signal }) => getChannelByUuid(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChannelByUuid>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChannelByUuidQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChannelByUuid>>
>;
export type GetChannelByUuidQueryError = unknown;

export function useGetChannelByUuid<
  TData = Awaited<ReturnType<typeof getChannelByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelByUuid>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelByUuid>>,
          TError,
          Awaited<ReturnType<typeof getChannelByUuid>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelByUuid<
  TData = Awaited<ReturnType<typeof getChannelByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelByUuid>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelByUuid>>,
          TError,
          Awaited<ReturnType<typeof getChannelByUuid>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelByUuid<
  TData = Awaited<ReturnType<typeof getChannelByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelByUuid>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 단건 조회
 */

export function useGetChannelByUuid<
  TData = Awaited<ReturnType<typeof getChannelByUuid>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelByUuid>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChannelByUuidQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 통계 조회
 */
export const getChannelStats = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<ChannelStatsResponse>(
    { url: `/channels/${uuid}/stats`, method: "GET", signal },
    options,
  );
};

export const getGetChannelStatsQueryKey = (uuid?: string) => {
  return [`/channels/${uuid}/stats`] as const;
};

export const getGetChannelStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getChannelStats>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelStats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChannelStatsQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannelStats>>> = ({
    signal,
  }) => getChannelStats(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChannelStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChannelStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChannelStats>>
>;
export type GetChannelStatsQueryError = unknown;

export function useGetChannelStats<
  TData = Awaited<ReturnType<typeof getChannelStats>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelStats>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelStats>>,
          TError,
          Awaited<ReturnType<typeof getChannelStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelStats<
  TData = Awaited<ReturnType<typeof getChannelStats>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelStats>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelStats>>,
          TError,
          Awaited<ReturnType<typeof getChannelStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelStats<
  TData = Awaited<ReturnType<typeof getChannelStats>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelStats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 통계 조회
 */

export function useGetChannelStats<
  TData = Awaited<ReturnType<typeof getChannelStats>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelStats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChannelStatsQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 프로필 이미지 조회
 */
export const getChannelProfile = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<Blob>(
    {
      url: `/channels/${uuid}/profile`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetChannelProfileQueryKey = (uuid?: string) => {
  return [`/channels/${uuid}/profile`] as const;
};

export const getGetChannelProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getChannelProfile>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelProfile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChannelProfileQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChannelProfile>>
  > = ({ signal }) => getChannelProfile(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChannelProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChannelProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChannelProfile>>
>;
export type GetChannelProfileQueryError = unknown;

export function useGetChannelProfile<
  TData = Awaited<ReturnType<typeof getChannelProfile>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelProfile>>,
          TError,
          Awaited<ReturnType<typeof getChannelProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelProfile<
  TData = Awaited<ReturnType<typeof getChannelProfile>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelProfile>>,
          TError,
          Awaited<ReturnType<typeof getChannelProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelProfile<
  TData = Awaited<ReturnType<typeof getChannelProfile>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelProfile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 프로필 이미지 조회
 */

export function useGetChannelProfile<
  TData = Awaited<ReturnType<typeof getChannelProfile>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelProfile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChannelProfileQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널의 플랫폼 목록 조회
 */
export const getChannelPlatforms = (
  uuid: string,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<ChannelPlatformResponse[]>(
    { url: `/channels/${uuid}/platforms`, method: "GET", signal },
    options,
  );
};

export const getGetChannelPlatformsQueryKey = (uuid?: string) => {
  return [`/channels/${uuid}/platforms`] as const;
};

export const getGetChannelPlatformsQueryOptions = <
  TData = Awaited<ReturnType<typeof getChannelPlatforms>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelPlatforms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChannelPlatformsQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChannelPlatforms>>
  > = ({ signal }) => getChannelPlatforms(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChannelPlatforms>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChannelPlatformsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChannelPlatforms>>
>;
export type GetChannelPlatformsQueryError = unknown;

export function useGetChannelPlatforms<
  TData = Awaited<ReturnType<typeof getChannelPlatforms>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelPlatforms>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelPlatforms>>,
          TError,
          Awaited<ReturnType<typeof getChannelPlatforms>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelPlatforms<
  TData = Awaited<ReturnType<typeof getChannelPlatforms>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelPlatforms>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelPlatforms>>,
          TError,
          Awaited<ReturnType<typeof getChannelPlatforms>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelPlatforms<
  TData = Awaited<ReturnType<typeof getChannelPlatforms>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelPlatforms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널의 플랫폼 목록 조회
 */

export function useGetChannelPlatforms<
  TData = Awaited<ReturnType<typeof getChannelPlatforms>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelPlatforms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChannelPlatformsQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
