/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminChannelPlatformCreateRequest,
  AdminChannelPlatformResponse,
  AdminChannelPlatformUpdateRequest,
  PageAdminChannelPlatformResponse,
  SearchAdminChannelPlatformsParams,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 채널 플랫폼 단건 조회
 */
export const getAdminChannelPlatformById = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminChannelPlatformResponse>(
    { url: `/admin/channel-platforms/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetAdminChannelPlatformByIdQueryKey = (id?: number) => {
  return [`/admin/channel-platforms/${id}`] as const;
};

export const getGetAdminChannelPlatformByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminChannelPlatformByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminChannelPlatformById>>
  > = ({ signal }) => getAdminChannelPlatformById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminChannelPlatformByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminChannelPlatformById>>
>;
export type GetAdminChannelPlatformByIdQueryError = unknown;

export function useGetAdminChannelPlatformById<
  TData = Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
          TError,
          Awaited<ReturnType<typeof getAdminChannelPlatformById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminChannelPlatformById<
  TData = Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
          TError,
          Awaited<ReturnType<typeof getAdminChannelPlatformById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminChannelPlatformById<
  TData = Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 플랫폼 단건 조회
 */

export function useGetAdminChannelPlatformById<
  TData = Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminChannelPlatformById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminChannelPlatformByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 플랫폼 수정
 */
export const updateAdminChannelPlatform = (
  id: number,
  adminChannelPlatformUpdateRequest: AdminChannelPlatformUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<AdminChannelPlatformResponse>(
    {
      url: `/admin/channel-platforms/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminChannelPlatformUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminChannelPlatformMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminChannelPlatform>>,
    TError,
    { id: number; data: AdminChannelPlatformUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminChannelPlatform>>,
  TError,
  { id: number; data: AdminChannelPlatformUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminChannelPlatform"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminChannelPlatform>>,
    { id: number; data: AdminChannelPlatformUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAdminChannelPlatform(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminChannelPlatformMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminChannelPlatform>>
>;
export type UpdateAdminChannelPlatformMutationBody =
  AdminChannelPlatformUpdateRequest;
export type UpdateAdminChannelPlatformMutationError = unknown;

/**
 * @summary 채널 플랫폼 수정
 */
export const useUpdateAdminChannelPlatform = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminChannelPlatform>>,
      TError,
      { id: number; data: AdminChannelPlatformUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminChannelPlatform>>,
  TError,
  { id: number; data: AdminChannelPlatformUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateAdminChannelPlatformMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채널 플랫폼 삭제
 */
export const deleteAdminChannelPlatform = (
  id: number,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    { url: `/admin/channel-platforms/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteAdminChannelPlatformMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminChannelPlatform>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdminChannelPlatform>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAdminChannelPlatform"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdminChannelPlatform>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAdminChannelPlatform(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdminChannelPlatformMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminChannelPlatform>>
>;

export type DeleteAdminChannelPlatformMutationError = unknown;

/**
 * @summary 채널 플랫폼 삭제
 */
export const useDeleteAdminChannelPlatform = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdminChannelPlatform>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdminChannelPlatform>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteAdminChannelPlatformMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채널 플랫폼 목록 조회
 */
export const searchAdminChannelPlatforms = (
  params: SearchAdminChannelPlatformsParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageAdminChannelPlatformResponse>(
    { url: `/admin/channel-platforms`, method: "GET", params, signal },
    options,
  );
};

export const getSearchAdminChannelPlatformsQueryKey = (
  params?: SearchAdminChannelPlatformsParams,
) => {
  return [`/admin/channel-platforms`, ...(params ? [params] : [])] as const;
};

export const getSearchAdminChannelPlatformsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
  TError = unknown,
>(
  params: SearchAdminChannelPlatformsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminChannelPlatformsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminChannelPlatforms>>
  > = ({ signal }) =>
    searchAdminChannelPlatforms(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminChannelPlatformsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminChannelPlatforms>>
>;
export type SearchAdminChannelPlatformsQueryError = unknown;

export function useSearchAdminChannelPlatforms<
  TData = Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
  TError = unknown,
>(
  params: SearchAdminChannelPlatformsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
          TError,
          Awaited<ReturnType<typeof searchAdminChannelPlatforms>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminChannelPlatforms<
  TData = Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
  TError = unknown,
>(
  params: SearchAdminChannelPlatformsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
          TError,
          Awaited<ReturnType<typeof searchAdminChannelPlatforms>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminChannelPlatforms<
  TData = Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
  TError = unknown,
>(
  params: SearchAdminChannelPlatformsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 플랫폼 목록 조회
 */

export function useSearchAdminChannelPlatforms<
  TData = Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
  TError = unknown,
>(
  params: SearchAdminChannelPlatformsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminChannelPlatforms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminChannelPlatformsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널 플랫폼 생성
 */
export const createAdminChannelPlatform = (
  adminChannelPlatformCreateRequest: AdminChannelPlatformCreateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<AdminChannelPlatformResponse>(
    {
      url: `/admin/channel-platforms`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: adminChannelPlatformCreateRequest,
      signal,
    },
    options,
  );
};

export const getCreateAdminChannelPlatformMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAdminChannelPlatform>>,
    TError,
    { data: AdminChannelPlatformCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAdminChannelPlatform>>,
  TError,
  { data: AdminChannelPlatformCreateRequest },
  TContext
> => {
  const mutationKey = ["createAdminChannelPlatform"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAdminChannelPlatform>>,
    { data: AdminChannelPlatformCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createAdminChannelPlatform(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAdminChannelPlatformMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAdminChannelPlatform>>
>;
export type CreateAdminChannelPlatformMutationBody =
  AdminChannelPlatformCreateRequest;
export type CreateAdminChannelPlatformMutationError = unknown;

/**
 * @summary 채널 플랫폼 생성
 */
export const useCreateAdminChannelPlatform = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAdminChannelPlatform>>,
      TError,
      { data: AdminChannelPlatformCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAdminChannelPlatform>>,
  TError,
  { data: AdminChannelPlatformCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateAdminChannelPlatformMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
