/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Stream Archive API
 * 멀티 플랫폼 스트리밍 녹화 시스템 API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetAdminAutoDeletePreviewParams,
  GetAdminAutoDeletePreviewSummaryParams,
  PageVideoAutoDeleteHistorySearchResponse,
  PageVideoAutoDeletePreviewResponse,
  SearchAdminAutoDeleteHistoriesParams,
  VideoAutoDeleteChannelPolicySearchResponse,
  VideoAutoDeletePolicyGetResponse,
  VideoAutoDeletePolicyUpdateRequest,
  VideoAutoDeletePolicyUpdateResponse,
  VideoAutoDeletePreviewSummaryResponse,
  VideoAutoDeleteRunResponse,
} from "../../models";

import { customAxiosInstance } from "../../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 전체 자동 삭제 정책 조회
 */
export const getAdminAutoDeleteGlobalPolicy = (
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoAutoDeletePolicyGetResponse>(
    { url: `/admin/videos/auto-delete/policy`, method: "GET", signal },
    options,
  );
};

export const getGetAdminAutoDeleteGlobalPolicyQueryKey = () => {
  return [`/admin/videos/auto-delete/policy`] as const;
};

export const getGetAdminAutoDeleteGlobalPolicyQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminAutoDeleteGlobalPolicyQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>
  > = ({ signal }) => getAdminAutoDeleteGlobalPolicy(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminAutoDeleteGlobalPolicyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>
>;
export type GetAdminAutoDeleteGlobalPolicyQueryError = unknown;

export function useGetAdminAutoDeleteGlobalPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeleteGlobalPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeleteGlobalPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 전체 자동 삭제 정책 조회
 */

export function useGetAdminAutoDeleteGlobalPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteGlobalPolicy>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminAutoDeleteGlobalPolicyQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 전체 자동 삭제 정책 설정
 */
export const updateAdminAutoDeleteGlobalPolicy = (
  videoAutoDeletePolicyUpdateRequest: VideoAutoDeletePolicyUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<VideoAutoDeletePolicyUpdateResponse>(
    {
      url: `/admin/videos/auto-delete/policy`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: videoAutoDeletePolicyUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminAutoDeleteGlobalPolicyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminAutoDeleteGlobalPolicy>>,
    TError,
    { data: VideoAutoDeletePolicyUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminAutoDeleteGlobalPolicy>>,
  TError,
  { data: VideoAutoDeletePolicyUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminAutoDeleteGlobalPolicy"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminAutoDeleteGlobalPolicy>>,
    { data: VideoAutoDeletePolicyUpdateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateAdminAutoDeleteGlobalPolicy(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminAutoDeleteGlobalPolicyMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminAutoDeleteGlobalPolicy>>
>;
export type UpdateAdminAutoDeleteGlobalPolicyMutationBody =
  VideoAutoDeletePolicyUpdateRequest;
export type UpdateAdminAutoDeleteGlobalPolicyMutationError = unknown;

/**
 * @summary 전체 자동 삭제 정책 설정
 */
export const useUpdateAdminAutoDeleteGlobalPolicy = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminAutoDeleteGlobalPolicy>>,
      TError,
      { data: VideoAutoDeletePolicyUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminAutoDeleteGlobalPolicy>>,
  TError,
  { data: VideoAutoDeletePolicyUpdateRequest },
  TContext
> => {
  const mutationOptions =
    getUpdateAdminAutoDeleteGlobalPolicyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채널별 자동 삭제 정책 조회
 */
export const getAdminAutoDeleteChannelPolicy = (
  channelId: number,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoAutoDeletePolicyGetResponse>(
    {
      url: `/admin/videos/auto-delete/policy/channels/${channelId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetAdminAutoDeleteChannelPolicyQueryKey = (
  channelId?: number,
) => {
  return [`/admin/videos/auto-delete/policy/channels/${channelId}`] as const;
};

export const getGetAdminAutoDeleteChannelPolicyQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
  TError = unknown,
>(
  channelId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAdminAutoDeleteChannelPolicyQueryKey(channelId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>
  > = ({ signal }) =>
    getAdminAutoDeleteChannelPolicy(channelId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!channelId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminAutoDeleteChannelPolicyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>
>;
export type GetAdminAutoDeleteChannelPolicyQueryError = unknown;

export function useGetAdminAutoDeleteChannelPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
  TError = unknown,
>(
  channelId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeleteChannelPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
  TError = unknown,
>(
  channelId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeleteChannelPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
  TError = unknown,
>(
  channelId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널별 자동 삭제 정책 조회
 */

export function useGetAdminAutoDeleteChannelPolicy<
  TData = Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
  TError = unknown,
>(
  channelId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeleteChannelPolicy>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminAutoDeleteChannelPolicyQueryOptions(
    channelId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널별 자동 삭제 정책 설정
 */
export const updateAdminAutoDeleteChannelPolicy = (
  channelId: number,
  videoAutoDeletePolicyUpdateRequest: VideoAutoDeletePolicyUpdateRequest,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<VideoAutoDeletePolicyUpdateResponse>(
    {
      url: `/admin/videos/auto-delete/policy/channels/${channelId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: videoAutoDeletePolicyUpdateRequest,
    },
    options,
  );
};

export const getUpdateAdminAutoDeleteChannelPolicyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminAutoDeleteChannelPolicy>>,
    TError,
    { channelId: number; data: VideoAutoDeletePolicyUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminAutoDeleteChannelPolicy>>,
  TError,
  { channelId: number; data: VideoAutoDeletePolicyUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateAdminAutoDeleteChannelPolicy"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminAutoDeleteChannelPolicy>>,
    { channelId: number; data: VideoAutoDeletePolicyUpdateRequest }
  > = (props) => {
    const { channelId, data } = props ?? {};

    return updateAdminAutoDeleteChannelPolicy(channelId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminAutoDeleteChannelPolicyMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminAutoDeleteChannelPolicy>>
>;
export type UpdateAdminAutoDeleteChannelPolicyMutationBody =
  VideoAutoDeletePolicyUpdateRequest;
export type UpdateAdminAutoDeleteChannelPolicyMutationError = unknown;

/**
 * @summary 채널별 자동 삭제 정책 설정
 */
export const useUpdateAdminAutoDeleteChannelPolicy = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAdminAutoDeleteChannelPolicy>>,
      TError,
      { channelId: number; data: VideoAutoDeletePolicyUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminAutoDeleteChannelPolicy>>,
  TError,
  { channelId: number; data: VideoAutoDeletePolicyUpdateRequest },
  TContext
> => {
  const mutationOptions =
    getUpdateAdminAutoDeleteChannelPolicyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채널별 자동 삭제 정책 삭제 (전체 기본값 따름)
 */
export const deleteAdminAutoDeleteChannelPolicy = (
  channelId: number,
  options?: SecondParameter<typeof customAxiosInstance>,
) => {
  return customAxiosInstance<void>(
    {
      url: `/admin/videos/auto-delete/policy/channels/${channelId}`,
      method: "DELETE",
    },
    options,
  );
};

export const getDeleteAdminAutoDeleteChannelPolicyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminAutoDeleteChannelPolicy>>,
    TError,
    { channelId: number },
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdminAutoDeleteChannelPolicy>>,
  TError,
  { channelId: number },
  TContext
> => {
  const mutationKey = ["deleteAdminAutoDeleteChannelPolicy"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdminAutoDeleteChannelPolicy>>,
    { channelId: number }
  > = (props) => {
    const { channelId } = props ?? {};

    return deleteAdminAutoDeleteChannelPolicy(channelId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdminAutoDeleteChannelPolicyMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminAutoDeleteChannelPolicy>>
>;

export type DeleteAdminAutoDeleteChannelPolicyMutationError = unknown;

/**
 * @summary 채널별 자동 삭제 정책 삭제 (전체 기본값 따름)
 */
export const useDeleteAdminAutoDeleteChannelPolicy = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdminAutoDeleteChannelPolicy>>,
      TError,
      { channelId: number },
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdminAutoDeleteChannelPolicy>>,
  TError,
  { channelId: number },
  TContext
> => {
  const mutationOptions =
    getDeleteAdminAutoDeleteChannelPolicyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 자동 삭제 즉시 실행
 */
export const runAdminAutoDelete = (
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoAutoDeleteRunResponse>(
    { url: `/admin/videos/auto-delete/run`, method: "POST", signal },
    options,
  );
};

export const getRunAdminAutoDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runAdminAutoDelete>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runAdminAutoDelete>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["runAdminAutoDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runAdminAutoDelete>>,
    void
  > = () => {
    return runAdminAutoDelete(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunAdminAutoDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof runAdminAutoDelete>>
>;

export type RunAdminAutoDeleteMutationError = unknown;

/**
 * @summary 자동 삭제 즉시 실행
 */
export const useRunAdminAutoDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof runAdminAutoDelete>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof runAdminAutoDelete>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getRunAdminAutoDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 자동 삭제 미리보기 목록 (다음 삭제 대상 동영상)
 */
export const getAdminAutoDeletePreview = (
  params: GetAdminAutoDeletePreviewParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageVideoAutoDeletePreviewResponse>(
    { url: `/admin/videos/auto-delete/preview`, method: "GET", params, signal },
    options,
  );
};

export const getGetAdminAutoDeletePreviewQueryKey = (
  params?: GetAdminAutoDeletePreviewParams,
) => {
  return [
    `/admin/videos/auto-delete/preview`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAdminAutoDeletePreviewQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
  TError = unknown,
>(
  params: GetAdminAutoDeletePreviewParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAdminAutoDeletePreviewQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminAutoDeletePreview>>
  > = ({ signal }) => getAdminAutoDeletePreview(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminAutoDeletePreviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminAutoDeletePreview>>
>;
export type GetAdminAutoDeletePreviewQueryError = unknown;

export function useGetAdminAutoDeletePreview<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
  TError = unknown,
>(
  params: GetAdminAutoDeletePreviewParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeletePreview>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeletePreview<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
  TError = unknown,
>(
  params: GetAdminAutoDeletePreviewParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeletePreview>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeletePreview<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
  TError = unknown,
>(
  params: GetAdminAutoDeletePreviewParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 자동 삭제 미리보기 목록 (다음 삭제 대상 동영상)
 */

export function useGetAdminAutoDeletePreview<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
  TError = unknown,
>(
  params: GetAdminAutoDeletePreviewParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreview>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminAutoDeletePreviewQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 자동 삭제 미리보기 요약 (다음 삭제 대상 개수·용량)
 */
export const getAdminAutoDeletePreviewSummary = (
  params?: GetAdminAutoDeletePreviewSummaryParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoAutoDeletePreviewSummaryResponse>(
    {
      url: `/admin/videos/auto-delete/preview/summary`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetAdminAutoDeletePreviewSummaryQueryKey = (
  params?: GetAdminAutoDeletePreviewSummaryParams,
) => {
  return [
    `/admin/videos/auto-delete/preview/summary`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAdminAutoDeletePreviewSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
  TError = unknown,
>(
  params?: GetAdminAutoDeletePreviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAdminAutoDeletePreviewSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>
  > = ({ signal }) =>
    getAdminAutoDeletePreviewSummary(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminAutoDeletePreviewSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>
>;
export type GetAdminAutoDeletePreviewSummaryQueryError = unknown;

export function useGetAdminAutoDeletePreviewSummary<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
  TError = unknown,
>(
  params: undefined | GetAdminAutoDeletePreviewSummaryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeletePreviewSummary<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
  TError = unknown,
>(
  params?: GetAdminAutoDeletePreviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
          TError,
          Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminAutoDeletePreviewSummary<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
  TError = unknown,
>(
  params?: GetAdminAutoDeletePreviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 자동 삭제 미리보기 요약 (다음 삭제 대상 개수·용량)
 */

export function useGetAdminAutoDeletePreviewSummary<
  TData = Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
  TError = unknown,
>(
  params?: GetAdminAutoDeletePreviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdminAutoDeletePreviewSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAdminAutoDeletePreviewSummaryQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채널별 자동 삭제 정책 목록 조회
 */
export const searchAdminAutoDeleteChannelPolicies = (
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<VideoAutoDeleteChannelPolicySearchResponse[]>(
    { url: `/admin/videos/auto-delete/policy/channels`, method: "GET", signal },
    options,
  );
};

export const getSearchAdminAutoDeleteChannelPoliciesQueryKey = () => {
  return [`/admin/videos/auto-delete/policy/channels`] as const;
};

export const getSearchAdminAutoDeleteChannelPoliciesQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminAutoDeleteChannelPoliciesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>
  > = ({ signal }) =>
    searchAdminAutoDeleteChannelPolicies(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminAutoDeleteChannelPoliciesQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>
>;
export type SearchAdminAutoDeleteChannelPoliciesQueryError = unknown;

export function useSearchAdminAutoDeleteChannelPolicies<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
          TError,
          Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminAutoDeleteChannelPolicies<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
          TError,
          Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminAutoDeleteChannelPolicies<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널별 자동 삭제 정책 목록 조회
 */

export function useSearchAdminAutoDeleteChannelPolicies<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteChannelPolicies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getSearchAdminAutoDeleteChannelPoliciesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 자동 삭제 이력 조회
 */
export const searchAdminAutoDeleteHistories = (
  params: SearchAdminAutoDeleteHistoriesParams,
  options?: SecondParameter<typeof customAxiosInstance>,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<PageVideoAutoDeleteHistorySearchResponse>(
    {
      url: `/admin/videos/auto-delete/histories`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getSearchAdminAutoDeleteHistoriesQueryKey = (
  params?: SearchAdminAutoDeleteHistoriesParams,
) => {
  return [
    `/admin/videos/auto-delete/histories`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSearchAdminAutoDeleteHistoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
  TError = unknown,
>(
  params: SearchAdminAutoDeleteHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchAdminAutoDeleteHistoriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>
  > = ({ signal }) =>
    searchAdminAutoDeleteHistories(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchAdminAutoDeleteHistoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>
>;
export type SearchAdminAutoDeleteHistoriesQueryError = unknown;

export function useSearchAdminAutoDeleteHistories<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
  TError = unknown,
>(
  params: SearchAdminAutoDeleteHistoriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
          TError,
          Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminAutoDeleteHistories<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
  TError = unknown,
>(
  params: SearchAdminAutoDeleteHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
          TError,
          Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchAdminAutoDeleteHistories<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
  TError = unknown,
>(
  params: SearchAdminAutoDeleteHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 자동 삭제 이력 조회
 */

export function useSearchAdminAutoDeleteHistories<
  TData = Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
  TError = unknown,
>(
  params: SearchAdminAutoDeleteHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchAdminAutoDeleteHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchAdminAutoDeleteHistoriesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
